src/reader.c
test/reader.py

This allows to change the maximum buffer size for the hiredis parser from python. Can boost speeds when handling large amounts of data.

Exposed hiredis maxbuf settings in python

---

setup.py

An unsorted list of source files causes the object files to
be linked in the same (non-deterministic) order, which
causes the binaries to differ between builds.

Sort list of source files to allow reproducible building

---

src/hiredis.c

Hello,
I noticed a crash importing hiredis in a python debug build.  And here's a patch to fix the module init to do an incref before calling PyModule_AddObject which steals references.
best,
-Kirat

incref before PyModule_AddObject which steals references.

---

src/reader.c
test/reader.py

Len method is gonna be used to apply the proper back pressure in an ad-hoc implementation of the `StreamReader` of _Asyncio_ [1] for _aioredis_. By default in a normal situation, the `StreamReader` provided by _Asyncio_ uses the length of the internal buffer to decide if pause or resume the read from one socket. In the current scenario, using directly the buffer provided by _hiredis_ is necessary publish this method to keep offering that feature to the user.
[1] https://github.com/aio-libs/aioredis/pull/273/files#diff-16f7900982363b78a4e9a528f9dc825cR26

Expose len method to retrieve the buffer length

---

setup.py

A lot of the workarounds in the build file are a result of trying to build the C code as a separate static library from the extension. The same result can be obtained more simply by including these files directly in the extension.

Simplify build system

---

src/hiredis.c
src/hiredis.h

Previously, the variable could alias variables named state in other
shared objects, which was causing segfaults when imported after pytorch.
This change makes it less likely that they overlap and cause undefined
behavior.
See also pytorch/pytorch#11471

Rename `state` to `hiredis_py_module_state`

---

src/reader.c
test/reader.py

Fix non-utf8 reply parsing causing segmentation fault in Python 3 (in a better way)

---

src/reader.c
src/reader.h
test/reader.py

By default, if a Reader is configured with an encoding, all string
replies provided by reader.gets() will be decoded with the configured
encoding. There are some replies that we never want to decode.
This allows the client/user to override the default behavior
in these specific situations without having to manage multiple
reader instances.

add optional "shouldDecode" argument to Reader.gets()

---

README.md
src/reader.c
src/reader.h
test/reader.py

Add an `errors` argument to Reader objects to be used in conjunction with the `encoding` argument. Valid values for `errors` are `'strict'` (the default), `'replace'`, `'ignore'`, or `'backslashreplace'`. These four values are defined by Python: https://docs.python.org/3/howto/unicode.html#the-string-type 
Note this is a backwards incompatible change. Prior to this change hiredis-py would silence `UnicodeDecodeError`s and return the original `bytes` object. After this change, the default behavior is to raise the `UnicodeDecodeError` when a decoding error is encountered. This matches Python's default behavior. The user can alter the default behavior by specifying a different value to `errors` just like normal Python.
Fixes redis/hiredis-py#81

Unicode errors

---

setup.py

`setup.py` will fail on systems where the locale is not UTF-8 based, because it reads the `README.md` file as binary. These are rare and hopefully less common each day, but FreeBSD is still using C locale.

Bugfix: README.md has unicode in it

---

src/reader.c
test/reader.py

This patch provides three changes:
1. Adds the `Reader.set_encoding` method. This method accepts the "encoding"
and "errors" arguments, verifies that both are either NULL or found within
the codecs module and then updates the Reader's state to use the new values.
The motivation here is to allow a user to update the Reader's encoding
functionality at runtime, perhaps temporarily. redis-py plans to use this to provide
context manager support. Something like:
```python
client = redis.Redis(encoding="utf-8")
client.get("my-utf8-key")
with client.response_context(encoding=None) as no_decode_client:
no_decode_client.get("my-bytes-key")
```
In the above example, the context manager will call `Reader.set_encoding`,
passing the `encoding=None` argument to update the Reader state. When the
context …

Allow "encoding" and "errors" attributes to be updated at runtime

---

setup.py
src/reader.c
test/reader.py

The update required updating names of a few functions and adding support for a couple of new data types.
@ifduyue please take a look when you have a chance.
I guess this PR closes #66, resolves #84, closes #95, and resolves #100

Bump hiredis from 0.13.3 to 1.0.0

---

setup.py

Fix the following build failure on gcc 4.8 which is raised since version 2.0.0 and https://github.com/redis/hiredis-py/commit/9084152f624e8e593b4e86ddf8bd13329fdfc043:
```
vendor/hiredis/read.c: In function 'redisReaderFree':
vendor/hiredis/read.c:646:9: error: 'for' loop initial declarations are only allowed in C99 mode
for (int i = 0; i < r->tasks; i++) {
^
vendor/hiredis/read.c:646:9: note: use option -std=c99 or -std=gnu99 to compile your code
```
This build failure is raised because hiredis source code is built without C99: https://github.com/redis/hiredis/commit/13a35bdb64615e381c5e1151cdd4e78bba71a6db
Fixes:
- http://autobuild.buildroot.org/results/04cbcddf6d83ebad8c98400754f9445375e9e489
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

setup.py: fix build with gcc 4.8

---

.travis.yml
appveyor.yml
setup.py

From what I can see, this should add support for Python 3.10
Closes #116

Add support for Python 3.10

---

README.md
hiredis/hiredis.pyi
src/reader.c
src/reader.h
test/reader.py

As RESP3 has been introduced it has native boolean types, to be able to
differentiate between insufficient data in buffer and actual False value
add option to specify custom sentinel.
CamelCase is used to conform to other arguments naming.
Closes: #114

Allow to specify value returned by `gets` when not enough data is available

---

.github/release-drafter-config.yml
.github/workflows/release-drafter.yml

The release drafter is the current standard across redis clients for _starting_ to write better release notes. The drafter takes pull requests tagged as either _maintenance, bug, or feature_ and slots the item into the release notes, based on the pull request title.
After this merge, releases made via the release drafter will be able to publish to PyPi (pending changes there too).

Integrating release drafter

---

setup.py

This pull request updates the troves for PyPi. Firstly, we're adding a trove for the newly released 3.11. Additionally, links back to the project are part of this PR.
Finally, a the Python 3 :: Only trove was added, for those searching for libraries supporting only Python3.

Python 3.11 trove, and links back to the project

---

.gitmodules

In addition to bumping the vendored hiredis, I updated the location to point to the https origin. This eliminates the issue for not github/ssh users.
Closes #134

Supporting hiredis 1.1.0

---

.github/workflows/pypi-publish.yaml

This PR adds a job to the publish action which creates the sdist for publishing to pypi.  This allows support of more architectures and OSes which need to build the package.
The action runs to completion, until the actual publish step, as I can't really test that, but I expect it would work fine.  See https://github.com/stumpylog/hiredis-py/actions/runs/3795414052
Fixes #138

Restores publishing of source distribution

---

CHANGELOG.md
src/reader.c
tests/test_gc.py

Implement the necessary garbage collection mechanism, fixing #162 (and as a consequence also <https://github.com/redis/redis-py/issues/2693>).
Add a test to make sure garbage collection works properly.

Implement garbage collection support in Reader (#162)

---

.github/workflows/freebsd.yaml
.github/workflows/integration.yaml
README.md
hiredis/__init__.py

This makes it possible to run the test suite against an installed hiredis-py.

Use absolute imports and remove __init__.py from tests.

---

MANIFEST.in

Update the rules in `MANIFEST.in` to include the current `tests` directory in sdist archives.

Fix including tests in sdist

---

README.md

Exposing the latest release to pypy as a badge, in case it differs. The result of #171.
closes #171

Badge for latest released on Pypi

---

src/pack.c

Partially fixes #158.
* src/pack.c: Replace sdsalloc.h with alloc.h.
(pack_command): Replace s_malloc with hi_malloc.

pack: Replace sdsalloc.h with alloc.h

---

.github/workflows/REUSABLE-wheeler.yaml
.gitignore

The CI job that builds the wheel for Windows fails. Try to fix it.

Fix building the wheel for windows

---

.github/workflows/REUSABLE-wheeler.yaml
.github/workflows/integration.yaml
CHANGELOG.md
setup.py

Fixes #186
Updates CI to build cp313 wheels. Adds pypy-3.10 testing as well.
See also https://github.com/redis/hiredis-py/pull/174.
@chayim could you take a look?

Update Python 3.13 compatibility

---

hiredis/__init__.py
hiredis/hiredis.pyi
src/hiredis.c
src/reader.c
src/reader.h
tests/test_reader.py

Allow clients to distinguish between RESP3 arrays and PUSH types by introducing PushNotification type, which subclasses list.
Fix #128

Introduce new type for RESP3 PUSH notifications
